version: '3.1'

services:
  db:
    image: mysql
    container_name: exads-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: exads
      MYSQL_USER: exads
      MYSQL_PASSWORD: password
    volumes:
      - ./exads_test.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
    - 3306:3306

  adminer:
    image: adminer
    container_name: exads-adminer
    restart: always
    ports:
    - 8080:8080
